### ISSUE TITLE
Dependencies missing 404

### ISSUE THREAD

**Issue by Bubsy3D** [lenartbezek/LenchScripterMod#9]
http://lench4991.github.io/LenchScripterMod/files/
returns a 404 page, and thus the mod cannot download the dependencies needed to install this awesome mod

.
![gimme](https://user-images.githubusercontent.com/45088492/62418066-5efe8480-b62e-11e9-8a58-3f8e1fb7cc22.png)
![plsLench](https://user-images.githubusercontent.com/45088492/62418067-62920b80-b62e-11e9-8779-32f83d6a04d6.png)

pls i need them for SCIENCE!

**Comment by lenartbezek** [comment]
The downloads should work now. I've created a dummy repository https://github.com/lench4991/LenchScripterMod to help serving files through GH pages via the old URL. The issue stems from me renaming my main GitHub username and thus changing repository urls.

If this still doesn't work, try downloading files from here: https://github.com/lenartbezek/LenchScripterMod/tree/gh-pages/files
and place them in Mods/Resources/LenchScripter.
